# Generated by Django 3.1.6 on 2021-07-25 06:41

import common.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.CharField(default=common.utility.get_ulid, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='商品名')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('thumbnail_url', models.TextField(null=True, verbose_name='サムネイルURL')),
                ('description', models.TextField(null=True, verbose_name='説明文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
