# Generated by Django 3.1.6 on 2021-08-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210804_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(max_length=500, verbose_name='商品名'),
        ),
    ]
