# Generated by Django 3.1.6 on 2021-08-04 16:41

import common.utility
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210804_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='amazon_price',
            field=models.IntegerField(default=0, null=True, verbose_name='amazon最安値'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='id',
            field=models.CharField(default=common.utility.get_ulid, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(max_length=500, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='価格'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='rakuten_price',
            field=models.IntegerField(default=0, null=True, verbose_name='rakuten最安値'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='yahoo_price',
            field=models.IntegerField(default=0, null=True, verbose_name='yahoo最安値'),
        ),
    ]
