# Generated by Django 3.1.6 on 2021-08-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20210804_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='amazon_url',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='amazonURL'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='rakuten_url',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='rakutenURL'),
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='yahoo_url',
            field=models.TextField(default='', max_length=100, null=True, verbose_name='yahooURL'),
        ),
    ]
