# Generated by Django 3.1.6 on 2021-08-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_remove_reviewmodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
