# Generated by Django 3.1.6 on 2021-08-05 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_remove_reviewmodel_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewmodel',
            name='item_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemmodel'),
        ),
    ]
