# Generated by Django 3.1.6 on 2021-08-05 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_reviewmodel_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemmodel'),
        ),
    ]
