# Generated by Django 3.1.6 on 2021-08-05 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20210805_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='item_id',
            field=models.ForeignKey(db_column='item_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='item.itemmodel'),
        ),
    ]
