# Generated by Django 3.1.6 on 2021-08-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
