# Generated by Django 3.1.6 on 2021-08-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_auto_20210808_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_item',
            field=models.ManyToManyField(default='', to='item.ItemModel'),
        ),
    ]
