# Generated by Django 3.1.6 on 2021-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_auto_20210808_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_item',
            field=models.ManyToManyField(default='', null=True, to='item.ItemModel'),
        ),
    ]
