# Generated by Django 3.1.6 on 2021-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20210809_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_item',
            field=models.ManyToManyField(default=[], null=True, to='item.ItemModel'),
        ),
    ]
